project:
  type: book

book:
  title: "sta104.github.io"
  author: "Norah Jones"
  date: "08/03/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html: default


