project:
  type: book

book:
  title: "Introduction to Statistics for UiTM"
  author: "Kamarul Ariffin Mansor"
  date: "08/03/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html: default


